Algoritmo "quadrado_numeros"
// Crie um algoritmo que imprima o quadrado dos números de 1 a 20

Var

   i: inteiro

Inicio

      i <- 0

      escreval ("|-----------------------------------------|")
      escreval ("|---- Quadrado dos números de 1 a 20 -----|")
      escreval ("|-----------------------------------------|")
      escreval

      para i de 1 ate 20 faca
         escreval (i, "² = ", i^2)
      fimpara

Fimalgoritmo