Algoritmo "soma_1_ate_200"
// Crie um algoritmo que imprima todos os números de 1 até o número
// digitado pelo usuário e imprima a soma deles
Var

   i, soma, n: inteiro

Inicio

      i <- 0
      soma <- 0

      escreval ("Escreva um número: ")
      leia (n)
      para i de 1 ate n  faca
      escreval (soma, " + ", i, " = ", soma+i)
      soma <- soma + i
      fimpara


Fimalgoritmo